Repository Kernel360/F2_PLAY_BADMINTON_FE, pull requests merged in 2024-10, with the labels that each got.

#39 feat: 캘린더 컴포넌트 연동
  app/page.tsx
  components/DayCell.tsx
  components/ui/calendar.tsx
  package-lock.json
  package.json
Labels: beforeLunch🍕, feat✨

#43 feat: 멤버 페이지 생성
  app/(header)/club/member/MemberDropdown.tsx
  app/(header)/club/member/OneMemberInfo.tsx
  app/(header)/club/member/page.tsx
  components/ui/IconButton.tsx
Labels: 5PM🌝, feat✨

#40 feat: 동호회 생성 페이지 구현
  app/(header)/createClub/page.tsx
Labels: 5PM🌝, feat✨

#44 fix: 새로고침 했을 때 url 에 따라 탭 활성화되도록 수정
  app/(header)/club/layout.tsx
  middleware.ts
Labels: beforeLunch🍕, fix🛠️

#51 chore: Biome 린트 에러 적용
  app/(header)/club/layout.tsx
  app/(header)/club/member/MemberDropdown.tsx
  app/(header)/club/member/OneMemberInfo.tsx
  app/(header)/club/member/page.tsx
  app/(header)/createClub/page.tsx
  middleware.ts
Labels: chore🧹, now❗️

#52 design: 캘린더 UI 생성
  app/page.tsx
  components/DayCell.tsx
Labels: beforeLunch🍕, design🖌️

#49 feat: 마이 페이지 생성
  app/(header)/my/MyOneGameResult.tsx
  app/(header)/my/page.tsx
Labels: beforeLunch🍕, feat✨

#56 fix: 마이페이지 biome 에러 해결
  app/(header)/my/MyOneGameResult.tsx
  app/(header)/my/page.tsx
Labels: fix🛠️

#57 feat: 스케줄 페이지 생성
  app/(header)/club/schedule/ScheduleList.tsx
  app/(header)/club/schedule/page.tsx
  app/globals.css
Labels: 5PM🌝, feat✨

#60 refactor: 파일 이름 컨벤션에 맞게 수정
  app/(header)/club/member/MemberInfo.tsx
  app/(header)/club/member/page.tsx
  app/(header)/club/schedule/ScheduleLeagueModal.tsx
  app/(header)/club/schedule/ScheduleOneGameInfo.tsx
  app/(header)/club/schedule/ScheduleOneGameResult.tsx
Labels: now❗️, refactor✍️

#63 chore: dark 모드 코드 주석 처리
  app/globals.css
Labels: chore🧹

#59 feat: 마이페이지 정보 수정 기능 구현
  app/(header)/my/page.tsx
Labels: 5PM🌝, feat✨

#67 feat: 캘린더와 스케줄 리스트 연동
  app/(header)/club/schedule/ScheduleList.tsx
  app/(header)/club/schedule/page.tsx
Labels: 5PM🌝

#68 feat: 헤더 검색창 조건부 렌더링
  components/ui/Header.tsx
Labels: 5PM🌝

#69 feat: 리그 정보 페이지 추가
  app/(header)/club/schedule/ScheduleList.tsx
  app/(header)/club/schedule/league/[leagueId]/page.tsx
Labels: 5PM🌝

#71 chore: 페이지 링크 연결
  components/clubs/ClubCard.tsx
  components/ui/Header.tsx
Labels: 5PM🌝, chore🧹

#73 feat: root page redirect 기능 추가
  app/page.tsx
Labels: 5PM🌝

#78 feat: 로그인을 위한 https 환경 세팅
  .gitignore
  constants/loginOauthUrl.ts
  package.json
Labels: 5PM🌝, feat✨

#80 design: 리그 정보 UI 작업
  app/(header)/club/schedule/ScheduleList.tsx
  app/(header)/club/schedule/league/[leagueId]/page.tsx
  utils/getTierWithEmoji.ts
Labels: beforeLunch🍕, design🖌️

#79 design: 소개 페이지 UI 작업
  app/(header)/club/intro/page.tsx
Labels: 5PM🌝, design🖌️

#84 fix: textarea 에러 수정
  app/(header)/club/intro/page.tsx
Labels: fix🛠️, hotfix🥵

#86 chore: react hook form 설치
  package-lock.json
  package.json
Labels: chore🧹

#89 design: 동호회 관리 페이지 UI 변경
  app/(header)/club/manage/page.tsx
  components/common/clubInfoInput/ClubInfoInputDescription.tsx
  components/common/clubInfoInput/ClubInfoInputImage.tsx
  components/common/clubInfoInput/ClubInfoInputName.tsx
Labels: 5PM🌝, design🖌️

#96 feat: 스케줄 생성 페이지 구현
  app/(header)/club/schedule/ScheduleList.tsx
  app/(header)/club/schedule/create/page.tsx
  components/ui/IconButton.tsx
  components/ui/Input.tsx
  components/ui/dropdown-menu.tsx
  components/ui/popover.tsx
  package-lock.json
  package.json
Labels: beforeLunch🍕, feat✨, design🖌️

#99 chore: openapi-ts 패키지 설치
  app/(header)/club/schedule/create/page.tsx
  components/DayCell.tsx
  package-lock.json
  package.json
  schemas/schema.d.ts
  tsconfig.json
Labels: 5PM🌝, chore🧹

#95 design: 동호회 생성 페이지 UI 작업
  app/(header)/createClub/page.tsx
  components/common/clubInfoInput/ClubInfoInputDescription.tsx
  components/common/clubInfoInput/ClubInfoInputName.tsx
Labels: 5PM🌝, design🖌️

#94 design: 멤버 페이지 UI 작업
  app/(header)/club/member/MemberDropdown.tsx
  app/(header)/club/member/MemberInfo.tsx
  app/(header)/club/member/MemberRollModal.tsx
  app/(header)/club/member/MemberSuspendedModal.tsx
  app/(header)/club/member/page.tsx
Labels: 5PM🌝, design🖌️

#100 feat: 전체 동호회 조회 API 연동
  app/(header)/clubs/page.tsx
  lib/api/functions/clubFn.ts
  lib/api/hooks/clubHook.ts
Labels: 5PM🌝, feat✨

#102 refactor: 폴더 구조 변경
  app/(header)/club/[clubId]/layout.tsx
  app/(header)/club/[clubId]/page.tsx
  app/(header)/club/create/page.tsx
  app/(header)/clubs/page.tsx
  app/(header)/layout.tsx
  app/(header)/my-club/ClubIntroPage.tsx
  app/(header)/my-club/layout.tsx
  app/(header)/my-club/manage/page.tsx
  app/(header)/my-club/member/MemberDropdown.tsx
  app/(header)/my-club/member/MemberInfo.tsx
  app/(header)/my-club/member/MemberRollModal.tsx
  app/(header)/my-club/member/MemberSuspendedModal.tsx
  app/(header)/my-club/member/page.tsx
  app/(header)/my-club/page.tsx
  app/(header)/my-club/schedule/ScheduleLeagueModal.tsx
  app/(header)/my-club/schedule/ScheduleList.tsx
  app/(header)/my-club/schedule/ScheduleOneGameInfo.tsx
  app/(header)/my-club/schedule/ScheduleOneGameResult.tsx
  app/(header)/my-club/schedule/[leagueId]/page.tsx
  app/(header)/my-club/schedule/create/page.tsx
  app/(header)/my-club/schedule/page.tsx
  app/layout.tsx
  app/page.tsx
  components/clubs/ClubCard.tsx
  components/ui/Header.tsx
  layouts/ClubLayout.tsx
Labels: now❗️

#110 fix: 배포 시 나는 에러 해결
  app/(header)/my-club/schedule/create/page.tsx
Labels: now❗️

#112 feat: 대진표 화면 및 기능 구현
  app/(header)/my-club/schedule/[leagueId]/match/MatchProfileDoubles.tsx
  app/(header)/my-club/schedule/[leagueId]/match/MatchProfileSingles.tsx
  app/(header)/my-club/schedule/[leagueId]/match/MatchScoreModalDoubles.tsx
  app/(header)/my-club/schedule/[leagueId]/match/MatchScoreModalSingles.tsx
  app/(header)/my-club/schedule/[leagueId]/match/page.tsx
  app/(header)/my-club/schedule/[leagueId]/page.tsx
Labels: beforeLunch🍕, feat✨

#115 feat: 멤버 페이지 API 연동
  app/(header)/my-club/member/MemberInfo.tsx
  app/(header)/my-club/member/page.tsx
  lib/api/functions/clubMemberFn.ts
  lib/api/hooks/clubMemberHook.ts
Labels: 5PM🌝, feat✨

#123 refactor: 폴더 구조 변경
  app/(header)/club/[clubId]/ClubIntroPage.tsx
  app/(header)/club/[clubId]/layout.tsx
  app/(header)/club/[clubId]/manage/page.tsx
  app/(header)/club/[clubId]/member/MemberDropdown.tsx
  app/(header)/club/[clubId]/member/MemberInfo.tsx
  app/(header)/club/[clubId]/member/MemberRollModal.tsx
  app/(header)/club/[clubId]/member/MemberSuspendedModal.tsx
  app/(header)/club/[clubId]/member/page.tsx
  app/(header)/club/[clubId]/page.tsx
  app/(header)/club/[clubId]/schedule/ScheduleLeagueModal.tsx
  app/(header)/club/[clubId]/schedule/ScheduleList.tsx
  app/(header)/club/[clubId]/schedule/ScheduleOneGameInfo.tsx
  app/(header)/club/[clubId]/schedule/ScheduleOneGameResult.tsx
  app/(header)/club/[clubId]/schedule/[leagueId]/match/MatchProfileDoubles.tsx
  app/(header)/club/[clubId]/schedule/[leagueId]/match/MatchProfileSingles.tsx
  app/(header)/club/[clubId]/schedule/[leagueId]/match/MatchScoreModalDoubles.tsx
  app/(header)/club/[clubId]/schedule/[leagueId]/match/MatchScoreModalSingles.tsx
  app/(header)/club/[clubId]/schedule/[leagueId]/match/page.tsx
  app/(header)/club/[clubId]/schedule/[leagueId]/page.tsx
  app/(header)/club/[clubId]/schedule/create/page.tsx
  app/(header)/club/[clubId]/schedule/page.tsx
  app/(header)/club/create/page.tsx
  app/(header)/my-club/layout.tsx
  app/(header)/my-club/page.tsx
  components/clubs/ClubCard.tsx
  layouts/ClubLayout.tsx
Labels: now❗️

#127 feat: header 기능 추가
  components/ui/Header.tsx
Labels: now❗️

#125 feat: 동호회 소개 페이지 API 연동
  app/(header)/club/[clubId]/ClubIntroPage.tsx
  app/(header)/club/[clubId]/layout.tsx
  lib/api/functions/memberFn.ts
  lib/api/hooks/memberHook.ts
Labels: 5PM🌝, feat✨

#133 feat: 월별 경기 일정 조회
  app/(header)/club/[clubId]/schedule/page.tsx
  components/DayCell.tsx
  constants/loginOauthUrl.ts
  lib/api/functions/leagueFn.ts
  lib/api/hooks/leagueHook.ts
Labels: feat✨

#129 feat: 동호회 관리 페이지 API 연동
  app/(header)/club/[clubId]/layout.tsx
  app/(header)/club/[clubId]/manage/page.tsx
  components/common/clubInfoInput/ClubInfoInputName.tsx
  lib/api/functions/clubFn.ts
  lib/api/hooks/clubHook.ts
Labels: beforeLunch🍕, feat✨

#138 feat: 경기 일정 상세 조회 api 연동
  app/(header)/club/[clubId]/schedule/[leagueId]/page.tsx
  lib/api/functions/leagueFn.ts
  lib/api/hooks/leagueHook.ts
  schemas/schema.d.ts
Labels: feat✨

#142 feat: 동호회 가입 api 연동
  app/(header)/club/[clubId]/page.tsx
  components/ui/Header.tsx
  lib/api/functions/clubMemberFn.ts
  lib/api/hooks/clubMemberHook.ts
  lib/api/hooks/memberHook.ts
  lib/api/hooks/membersHook.ts
Labels: feat✨

#141 feat: 회원 관리 관련 API 연동
  app/(header)/club/[clubId]/member/MemberDropdown.tsx
  app/(header)/club/[clubId]/member/MemberExpelModal.tsx
  app/(header)/club/[clubId]/member/MemberInfo.tsx
  app/(header)/club/[clubId]/member/MemberRoleModal.tsx
  app/(header)/club/[clubId]/member/MemberRollModal.tsx
  app/(header)/club/[clubId]/member/MemberSuspendedModal.tsx
  app/(header)/club/[clubId]/member/page.tsx
  lib/api/functions/clubMemberFn.ts
  lib/api/hooks/clubMemberHook.ts
  schemas/schema.d.ts
Labels: beforeLunch🍕, feat✨

#149 feat: 권한에 따라 탭 레이아웃 다르게 보이게 하기
  app/(header)/club/[clubId]/layout.tsx
  app/layout.tsx
  components/ui/Header.tsx
  lib/api/functions/memberFn.ts
  lib/api/hooks/SessionHook.ts
Labels: feat✨

#150 feat: 경기 삭제 api 연동
  app/(header)/club/[clubId]/schedule/[leagueId]/page.tsx
  lib/api/functions/leagueFn.ts
  lib/api/hooks/leagueHook.ts
Labels: feat✨

#151 feat: 내정보 조회, 프로필사진 수정 api 연동
  app/(header)/my/page.tsx
  constants/loginOauthUrl.ts
  lib/api/functions/memberFn.ts
  lib/api/hooks/memberHook.ts
Labels: feat✨

#168 feat: 에러 핸들링 함수 구현
  app/(header)/club/[clubId]/page.tsx
  app/layout.tsx
  app/page.tsx
  components/ui/toast.tsx
  components/ui/toaster.tsx
  hooks/use-toast.ts
  lib/api/functions/clubFn.ts
  lib/api/hooks/clubHook.ts
  lib/api/hooks/useQueryWithToast.ts
  lib/api/restClient.ts
  package-lock.json
  package.json
Labels: feat✨

#169 feat: 새로운 메인 페이지 UI 완성
  app/(header)/club/[clubId]/page.tsx
  app/(header)/club/page.tsx
  app/(header)/my/page.tsx
  app/page.tsx
  components/DayCarousel.tsx
  components/ui/Header.tsx
  components/ui/badge.tsx
  components/ui/carousel.tsx
  constants/loginOauthUrl.ts
  lib/api/restClient.ts
  package-lock.json
  package.json
Labels: feat✨

#173 feat: 로그인 url 환경변수 설정
  .env.example
  components/pages/Login.tsx
Labels: feat✨
