Repository Kernel360/F2_PLAY_BADMINTON_FE, pull requests merged in 2024-09, with the labels that each got.

#3 feat: storybook과 shadcn을 이용하여 button 컴포넌트 생성
  .eslintrc.json
  .storybook/main.ts
  .storybook/preview.ts
  app/globals.css
  components/ui/button.stories.tsx
  components/ui/button.tsx
  package-lock.json
  package.json
  stories/Button.stories.ts
  stories/Button.tsx
  stories/Configure.mdx
  stories/Header.stories.ts
  stories/Header.tsx
  stories/Page.stories.ts
  stories/Page.tsx
  stories/assets/accessibility.png
  stories/assets/accessibility.svg
  stories/assets/addon-library.png
  stories/assets/assets.png
  stories/assets/avif-test-image.avif
  stories/assets/context.png
  stories/assets/discord.svg
  stories/assets/docs.png
  stories/assets/figma-plugin.png
  stories/assets/github.svg
  stories/assets/share.png
  stories/assets/styling.png
  stories/assets/testing.png
  stories/assets/theming.png
  stories/assets/tutorials.svg
  stories/assets/youtube.svg
  stories/button.css
  stories/header.css
  stories/page.css
  tailwind.config.ts
Labels: beforeLunch🍕, feat✨

#5 feat: Text Component 생성
  app/globals.css
  components/ui/Text.stories.tsx
  components/ui/Text.tsx
Labels: 5PM🌝, feat✨

#8 feat: 이미지 컴포넌트 생성하기
  components/ui/Image.stories.tsx
  components/ui/Image.tsx
Labels: 5PM🌝, feat✨

#7 feat: Input Component 생성
  app/globals.css
  components/ui/Button.stories.tsx
  components/ui/Button.tsx
  components/ui/Input.stories.tsx
  components/ui/Input.tsx
Labels: 5PM🌝, feat✨

#13 feat: Tab 컴포넌트 생성
  components/ui/Tabs.stories.tsx
  components/ui/Tabs.tsx
  package-lock.json
  package.json
Labels: beforeLunch🍕, feat✨

#17 refactor: Input 컴포넌트 search, icon props 추가
  components/ui/Input.stories.tsx
  components/ui/Input.tsx
Labels: 5PM🌝, refactor✍️

#15 feat: 이미지 카드 컴포넌트 생성
  components/ui/ImageCard.stories.tsx
  components/ui/ImageCard.tsx
Labels: 5PM🌝, feat✨

#20 feat: 헤더 컴포넌트 생성
  components/ui/Header.stories.tsx
  components/ui/Header.tsx
  components/ui/ImageCard.tsx
  components/ui/Input.stories.tsx
  components/ui/Input.tsx
  components/ui/Text.stories.tsx
  components/ui/Text.tsx
  types/layoutTypes.ts
Labels: 5PM🌝, feat✨

#23 feat: 탭 레이아웃 구현
  app/club/intro/pages.tsx
  app/club/layout.tsx
  app/club/pages.tsx
  app/layout.tsx
  app/page.tsx
  components/ui/Header.tsx
  components/ui/TabLayout.stories.tsx
  components/ui/Tabs.tsx
Labels: beforeLunch🍕, feat✨

#18 feat: Grid 컴포넌트 생성
  components/ui/Grid.stories.tsx
  components/ui/Grid.tsx
Labels: 5PM🌝, feat✨

#22 feat: IconButton 컴포넌트 생성
  components/ui/IconButton.stories.tsx
  components/ui/IconButton.tsx
Labels: 5PM🌝, feat✨

#27 feat: 동호회 리스트 페이지
  app/clubs/page.tsx
  app/images/dummy-image.jpg
  app/images/tier-bronze.png
  app/images/tier-gold.png
  app/images/tier-silver.png
  app/layout.tsx
  components/clubs/ClubCard.tsx
  components/ui/Grid.tsx
  components/ui/card.tsx
  types/images.d.ts
Labels: beforeLunch🍕, feat✨

#29 fix: pages폴더를 page로 변경
  app/club/intro/page.tsx
  app/club/page.tsx
  app/page.tsx
Labels: beforeLunch🍕

#37 fix: 레이아웃 변경
  app/(header)/club/intro/page.tsx
  app/(header)/club/layout.tsx
  app/(header)/club/manage/page.tsx
  app/(header)/club/member/page.tsx
  app/(header)/club/page.tsx
  app/(header)/club/schedule/page.tsx
  app/(header)/clubs/page.tsx
  app/(header)/layout.tsx
  app/club/intro/page.tsx
  app/club/layout.tsx
  app/club/page.tsx
  app/layout.tsx
  app/page.tsx
Labels: beforeLunch🍕, fix🛠️

#33 feat: 동호회 소개 화면 구현
  app/(header)/club/intro/page.tsx
Labels: 5PM🌝, feat✨

#36 feat: 동호회 관리 페이지 구현
  .eslintrc.json
  app/(header)/club/intro/page.tsx
  app/(header)/club/manage/page.tsx
  app/login/LoginButton.tsx
  app/login/page.tsx
  components/clubs/ClubCard.tsx
  public/images/dummy-image.jpg
  public/images/google-logo.png
  public/images/kakao-logo.png
  public/images/main-logo.png
  public/images/naver-logo.png
  public/images/tier-bronze.png
  public/images/tier-gold.png
  public/images/tier-silver.png
Labels: 5PM🌝, feat✨
